#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

trap "cd '${ORIG_DIR}'" EXIT

source ./create-network

# run nginx - port 8080
docker run --rm --name nginx-web-service \
  --network "${NETWORK_NAME}" \
  -v $PWD/nginx-web-service.conf:/etc/nginx/nginx.conf \
  -v $PWD/root:/docroot \
  -p 8080:80 \
  nginx
